site_name: TypeScript Challenge Answer

theme:
    name: material
    favicon: assets/images/favicon.png
    font:
        text: Roboto
        code: Roboto Mono
    custom_theme: custom_theme/
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - media: '(prefers-color-scheme: light)'
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    features:
        - content.code.copy

markdown_extensions:
    #  - smarty
    - footnotes
    - meta
    - md_in_html
    - toc:
          permalink: true
          baselevel: 3
          toc_depth: 4
    - tables
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.snippets:
          base_path:
              - ./docs
          check_paths: true
    # - pymdownx.emoji:
    #     emoji_generator: !!python/name:materialx.emoji.to_svg
    #     emoji_index: !!python/name:materialx.emoji.twemoji
    - pymdownx.tabbed:
          alternate_style: true
    - attr_list
nav:
    - Home: index.md
    - Easy:
          - Pick: easy/pick.md
          - Readonly: easy/readonly.md
          - Length of Tuple: easy/lengthOfTuple.md
extra_css: [assets/css/extra.css]

